theme: jekyll-theme-minimal

# Setup
title:        Donal Heidenblad
tagline:      Instructor and Technologist
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Donal Heidenblad
  url:        /about.html 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
