theme: jekyll-theme-minimal

# Setup
title:        Donal Heidenblad
tagline:      Instructor and Technologist
description:  
baseurl:      ""
paginate:     1
locale:       "en"

google_analytics: UA-49219513-1
logo: 
show_downloads:   "no"

# About/contact
author:
  name:       Donal Heidenblad
  url:        /about.html 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
