# Site settings
title: Donal Heidenblad
description: > # this means to ignore newlines until "baseurl:"
  Donal Heidenblad is a technologist with experience in project management, analysis, data wrangling, and programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://donal.us" # the base hostname & protocol for your site
github_username:  donalus
keybase_username:  donalus

# Build settings
markdown: kramdown
highlighter: rouge
