theme: jekyll-theme-cayman

# Setup
title:        Irreproducible Results
tagline:      A data and techology blog.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Donal Heidenblad
  url:        https://irreproducibleresults.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
